name: "Qmk Firmware Build Action"
description: "Building qmk firmware"
inputs:
  qmk_firmware_version:
    description: 'QMK Firmware version'
    required: false
  keyboard:
    description: 'Keyboard name'
    required: true
  rev:
    description: 'Keyboard revision name'
    required: true
  keymap:
    description: 'Keymap name'
    required: true

outputs:
  hex_file:
    description: 'Compiled firmeware file'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t custom_image \
          --build-arg qmk_firmware_version=${qmk_firmware_version} \
          .
      env:
        qmk_firmware_version: ${{ inputs.qmk_firmware_version || 'latest' }}
        keybaord: ${{ inputs.keyboard }}
        rev: ${{ inputs.rev }}
        keymap: ${{ inputs.keymap }}
      shell: bash

#   using: 'docker'
#   image: 'Dockerfile'
#   env:
#     qmk_firmware_version: ${{ inputs.qmk_firmware_version || 'latest' }}
#     keyboard: ${{ inputs.keyboard }}
#     rev: ${{ inputs.rev }}
#     keymap: ${{ inputs.keymap }}

branding:
  icon: "mic"
  color: "blue"
